

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAMES ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAMES ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findflann.cmake")
# Global approach
set(flann_FOUND 1)
set(flann_VERSION "1.9.1")

find_package_handle_standard_args(flann REQUIRED_VARS
                                  flann_VERSION VERSION_VAR flann_VERSION)
mark_as_advanced(flann_FOUND flann_VERSION)


set(flann_INCLUDE_DIRS "/home/sitavlas/.conan/data/flann/1.9.1/bashbug/stable/package/0ae23ce156a999016ff3644328f7150befab40a6/include")
set(flann_INCLUDE_DIR "/home/sitavlas/.conan/data/flann/1.9.1/bashbug/stable/package/0ae23ce156a999016ff3644328f7150befab40a6/include")
set(flann_INCLUDES "/home/sitavlas/.conan/data/flann/1.9.1/bashbug/stable/package/0ae23ce156a999016ff3644328f7150befab40a6/include")
set(flann_RES_DIRS )
set(flann_DEFINITIONS )
set(flann_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(flann_COMPILE_DEFINITIONS )
set(flann_COMPILE_OPTIONS_LIST "" "")
set(flann_COMPILE_OPTIONS_C "")
set(flann_COMPILE_OPTIONS_CXX "")
set(flann_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(flann_LIBRARIES "") # Will be filled later
set(flann_LIBS "") # Same as flann_LIBRARIES
set(flann_SYSTEM_LIBS )
set(flann_FRAMEWORK_DIRS )
set(flann_FRAMEWORKS )
set(flann_FRAMEWORKS_FOUND "") # Will be filled later
set(flann_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(flann_FRAMEWORKS_FOUND "${flann_FRAMEWORKS}" "${flann_FRAMEWORK_DIRS}")

mark_as_advanced(flann_INCLUDE_DIRS
                 flann_INCLUDE_DIR
                 flann_INCLUDES
                 flann_DEFINITIONS
                 flann_LINKER_FLAGS_LIST
                 flann_COMPILE_DEFINITIONS
                 flann_COMPILE_OPTIONS_LIST
                 flann_LIBRARIES
                 flann_LIBS
                 flann_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to flann_LIBS and flann_LIBRARY_LIST
set(flann_LIBRARY_LIST flann_cpp_s lz4)
set(flann_LIB_DIRS "/home/sitavlas/.conan/data/flann/1.9.1/bashbug/stable/package/0ae23ce156a999016ff3644328f7150befab40a6/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_flann_DEPENDENCIES "${flann_FRAMEWORKS_FOUND} ${flann_SYSTEM_LIBS} lz4::lz4")

conan_package_library_targets("${flann_LIBRARY_LIST}"  # libraries
                              "${flann_LIB_DIRS}"      # package_libdir
                              "${_flann_DEPENDENCIES}"  # deps
                              flann_LIBRARIES            # out_libraries
                              flann_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "flann")                                      # package_name

set(flann_LIBS ${flann_LIBRARIES})

foreach(_FRAMEWORK ${flann_FRAMEWORKS_FOUND})
    list(APPEND flann_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND flann_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${flann_SYSTEM_LIBS})
    list(APPEND flann_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND flann_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(flann_LIBRARIES_TARGETS "${flann_LIBRARIES_TARGETS};lz4::lz4")
set(flann_LIBRARIES "${flann_LIBRARIES};lz4::lz4")

set(CMAKE_MODULE_PATH "/home/sitavlas/.conan/data/flann/1.9.1/bashbug/stable/package/0ae23ce156a999016ff3644328f7150befab40a6/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/sitavlas/.conan/data/flann/1.9.1/bashbug/stable/package/0ae23ce156a999016ff3644328f7150befab40a6/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET flann::flann)
        add_library(flann::flann INTERFACE IMPORTED)
        if(flann_INCLUDE_DIRS)
            set_target_properties(flann::flann PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${flann_INCLUDE_DIRS}")
        endif()
        set_property(TARGET flann::flann PROPERTY INTERFACE_LINK_LIBRARIES
                     "${flann_LIBRARIES_TARGETS};${flann_LINKER_FLAGS_LIST}")
        set_property(TARGET flann::flann PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${flann_COMPILE_DEFINITIONS})
        set_property(TARGET flann::flann PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${flann_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT lz4_FOUND)
            find_dependency(lz4 REQUIRED)
        else()
            message(STATUS "Dependency lz4 already found")
        endif()

    endif()
endif()

foreach(_BUILD_MODULE_PATH ${flann_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
